fb55/htmlparser2

lib/Parser.js
It looks that the `xmlMode` option is `false` by default.
=> Fix a comment (xmlMode default)

.jscsrc
This key is overwritten two lines later (with a stricter setting).
=> Remove duplicate key entry in .jscsrc

lib/FeedHandler.js, lib/Parser.js, lib/Stream.js, lib/WritableStream.js, package.json
Hello,
I replaced `require("util").inherits` by `require("inherits")` which is more consistent with `readable-stream` usage and produce a smaller [browserify](http://browserify.org/) build.
`inherits` is already a `readable-stream` dependency.
Thank for your job on this lib ;)
=> Replace util.inherits

lib/Tokenizer.js, test/Events/32-script-ending-with-lessthan.json
This ensures that we catch the close tag when the special ends with a "<".  Fixes #165.
=> Consider "<" before checking if in a special

lib/WritableStream.js, test/unicode.js
http://stackoverflow.com/questions/12121775/convert-streamed-buffers-to-utf8-string
=> Use StringDecoder for Buffers in WritableStream

lib/Tokenizer.js
I had some problem in multiple write
```
doc.write(arg) ;
doc.write(arg1) ;
doc.write(arg2) ;
doc.write(arg3) ;
```
by looking at the code it seems it was due to 
```
this._index = 0;
this._bufferOffset += this._index;
```
which is obviously wrong.
by switching them to:
```
this._bufferOffset += this._index;
this._index = 0;
```
It worked. 
Here's my pull request.
=> Fixed write() problem

lib/Tokenizer.js, test/api.js
@gustavnikolaj and I ran into a problem where `endIndex` came out wrong for a tag that spanned multiple chunks. We tracked it down to something that looks like an obvious mistake.
=> Fix startIndex/endIndex when a tag is spread across multiple chunks

lib/WritableStream.js
According to the official repository of [nodejs/readable-stream](https://github.com/nodejs/readable-stream):
If you want to guarantee a stable streams base, regardless of what version of Node you, or the users of your libraries are using, use readable-stream only and avoid the "stream" module in Node-core.
Also, stream module does not exist anymore in Node 9+, breaking the library.
=> Remove require for stream

lib/Tokenizer.js, test/Events/33-cdata_more-edge-cases.json
The tokenizer stays in the AFTER_CDATA1 state after detecting a closing square bracket, even if no additional square and angled bracket follow. So it will detect any following square and angular bracket as CDATA end, even if there are arbitrary characters in between them.
In the scenario where a CDATA section includes multiple conditional comments (` ... `), the tokenizer will break out of the cdata section after it encounters the second `]>`. Please see the test case i added for this.
I fixed this by going back to the IN_CDATA state if no additional square bracket follows after the first one.
=> Fix premature cdata end detection with conditional comments

lib/Parser.js, test/Documents/Svg.html, test/Stream/06-Svg.json
SVG and MathML elements inside HTML documents always use XML rules for tag closing: any element can have children _or_ can be self-closing with a slash at the end of the start tag.
This PR removes SVG tags from the list of HTML void tags (which was breaking SVG parsing _even with_ `recognizeSelfClosing` set to true). Instead, the code keeps track of the tag names that switch in and out of this "XML-ish" parsing mode (here called `foreignContext` to be consistent with the HTML specs).
Fixes #187 (as well as bugs in various downstream libraries).
Includes tests adapted from PR #129, which is made obsolete. Existing tests, including linting, all still pass.
Note: There are still other issues with SVG/MathML parsing related to case sensitivity. But those can be avoided by setting the …
=> Correctly handle SVG (and MathML) tag closing

lib/Parser.js, test/Documents/Svg.html, test/Stream/06-Svg.json
Without this patch the context switches as soon as there's a title tag inside the svg but doesn't switch back on the closing title. So all self-closing svg tags like `path` break.
Relates to #254
=> Fix failing context switch 

lib/CollectingHandler.js, lib/Events.js, lib/ProxyHandler.js, lib/Stream.js, lib/index.js
rollup throws some warnings for the circular dependencies caused by importing EVENTS from the index.js that imports and re-exports each sub-module.
Warnings:
```
(!) Circular dependency: ../node_modules/htmlparser2/lib/index.js -> ../node_modules/htmlparser2/lib/Stream.js -> ../node_modules/htmlparser2/lib/index.js
(!) Circular dependency: ../node_modules/htmlparser2/lib/index.js -> ../node_modules/htmlparser2/lib/Stream.js -> commonjs-proxy:/Users/grudy/dev/stable/jsapp/node_modules/htmlparser2/lib/index.js -> ../node_modules/htmlparser2/lib/index.js
(!) Circular dependency: ../node_modules/htmlparser2/lib/index.js -> ../node_modules/htmlparser2/lib/ProxyHandler.js -> ../node_modules/htmlparser2/lib/index.js
(!) Circular dependency: ../node_modules/htmlparser2/lib/index.js -> …
```
=> Remove circular dependencies caused by EVENTS being imported from ./ and ../

README.md
I realized that `Parser` does not support streams by accident. I'd been sucessfully `piping` to `Parser` for quite some time and only now, when faced with multi-byte characters split over multiple chunks I realized, that I'd just been lucky. I think the `WritableStream` interface deserves a mention in the README. Especially when considering `readable.pipe(parser)` seems to be working, aside from the multibyte chars.
=> Explain stream usage in README

src/Tokenizer.spec.ts, src/Tokenizer.ts
Currently, self-closing special tags (`<script />`, `<style />`, and `<title />`) are not parsed correctly. The tags will be correctly handled as self-closing, but the rest of the input stream will be parsed as text. Technically self-closing special tags are not valid, but htmlparser2 allows all other tags to be self-closing and its not uncommon to encounter them in malformed HTML or in templates for various frontend frameworks.
**Root Cause:**
When the Tokenizer encounters the end of a self-closing special tag, it correctly issues callbacks for `onopentagname` and `onselfclosingtag`, then returns to the `Text` state. This is consistent with how it handles normal self-closing tags. However, it does not reset the value of `_special` which causes the `Text` state to ignore any additional …
=> Fix broken parsing after self-closing special tags

src/FeedHandler.ts, src/__fixtures__/Documents/RSS_Example.xml, src/__fixtures__/Stream/02-RSS.json
This is a retry of https://github.com/fb55/htmlparser2/pull/102/files based on the [Media RSS Specification](https://www.rssboard.org/media-rss#media-content).
=> Add media content parsing to FeedHandler

src/Tokenizer.ts, src/__fixtures__/Events/37-entity-in-title.json
=> fix(tokenizer): Parse entities in <title> tags

src/Tokenizer.ts
Callbacks interface is used in Tokenizer constructor, but was not exported.
=> Export Callbacks interface

src/Parser.ts
Allows users to override this method and get custom void-element behavior.
Fixes #767
=> feat(parser): Add `isVoidElement` method

src/FeedHandler.ts, src/__fixtures__/test-helper.ts
There is no point in having a handler for this, really.
`FeedHandler` is the reason why this library needs to keep a dependency on `domutils` and might be moved out of the module at some point.
=> refactor(feedhandler): Move logic of `FeedHandler` to function

src/Parser.spec.ts, src/Parser.ts
Reported by @thewilkybarkid in https://github.com/posthtml/posthtml-parser/pull/80#issuecomment-903320512
=> fix(parser): Index of closing tag was misaligned

src/Tokenizer.ts, src/__fixtures__/Events/37-entity-in-title.json, src/__fixtures__/Events/41-trailing-legacy-entity.json, src/__fixtures__/Events/42-trailing-numeric-entity.json
Changes relevant for people extending `Tokenizer`: `Tokenizer`'s `option` argument can no longer be `null`, and we no longer check for unknown states.
=> refactor(tokenizer): Remove unused branches, improve test coverage

src/Parser.spec.ts, src/Parser.ts, src/__fixtures__/Events/01-simple.json, src/__fixtures__/Events/02-template.json, src/__fixtures__/Events/03-lowercase_tags.json, src/__fixtures__/Events/04-cdata.json, src/__fixtures__/Events/05-cdata-special.json, src/__fixtures__/Events/07-self-closing.json, src/__fixtures__/Events/08-implicit-close-tags.json, src/__fixtures__/Events/09-attributes.json, src/__fixtures__/Events/10-crazy-attrib.json, src/__fixtures__/Events/11-script_in_script.json, src/__fixtures__/Events/12-long-comment-end.json, src/__fixtures__/Events/13-long-cdata-end.json, src/__fixtures__/Events/14-implicit-open-tags.json, src/__fixtures__/Events/16-double_attribs.json, src/__fixtures__/Events/21-entity_in_attribute.json, src/__fixtures__/Events/22-double_brackets.json, src/__fixtures__/Events/24-special_special.json, src/__fixtures__/Events/26-not-quite-closed.json, src/__fixtures__/Events/27-entities_in_attributes.json, src/__fixtures__/Events/32-script-ending-with-lessthan.json, src/__fixtures__/Events/35-non-br-void-close-tag.json, src/__fixtures__/Events/36-entity-in-attrib.json, src/__fixtures__/Events/37-entity-in-title.json, src/__fixtures__/Events/38-entity-in-title-no-decode.json, src/__fixtures__/Events/39-title-in-script.json, src/__fixtures__/Events/40-xml_tags.json, src/__fixtures__/Events/44-indices.json, src/__snapshots__/WritableStream.spec.ts.snap
Not added to `onopentagname`, as that event isn't very useful for determining indices.
=> feat(parser): Add `isImplied` flag to `onopentag`/`onclosetag`

src/Tokenizer.ts
Results in fewer slices & string concats
=> refactor(tokenizer): Emit text before entities once entity is confirmed

src/Parser.ts
Only `</p>` and `</br>` close tags result in implied open tags:
- [onclosetag logic for `p`](https://github.com/fb55/htmlparser2/blob/6445c32b05dc070049eeaaf201bfc123daca3d37/src/Parser.ts#L336)
- [onclosetag logic for `br`](https://github.com/fb55/htmlparser2/blob/6445c32b05dc070049eeaaf201bfc123daca3d37/src/Parser.ts#L340)
This commit clarifies this in the existing comments. It also
makes the special case nature of this more apparent by using
the literal values 'p' and 'br' instead of the variable `name`,
which is proven to have these values. This is less obfuscating.
=> refactor(parser): Highlight special close-implies-open logic

src/__fixtures__/Events/07a-end_slash--void.json, src/__fixtures__/Events/07b-end_slash--void_without.json, src/__fixtures__/Events/07c-end_slash--void_without--xmlMode.json, src/__fixtures__/Events/07d-end_slash--non_void.json, src/__fixtures__/Events/07e-end_slash--non_void--xmlmode.json, src/__fixtures__/Events/07f-end_slash--non_void--recognize_self_closing.json, src/__fixtures__/Events/07g-end_slash--consumed_by_attrib_value_in_void.json, src/__fixtures__/Events/07h-end_slash--consumed_by_attrib_value_in_non_void.json
This PR contains suggested enhancements to the `Events/07-self-closing.json`  test.
It also suggests a testing strategy that can be applied in other cases: a set of tests where the input and context are identical except for one isolated change. The outputs can thereby be diffed, showing the effect of the isolated change.
No worries if this isn't merged. Also happy to make any changes desired changes. 
The original `07-self-closing.json` covered two cases:
- a tag ending in `/>` but where the `/` is in fact part of the attribute value -- thus *not* a self-closing tag
- an HTML void element, `<hr>`, in XHTML self-closing style.
One flaw with this test is that `hr` is also a void element: While the test passes because the expected `closetag` event occurs, one doesn't know if it occurs …
=> tests: update Events/07 test to clarify interpretation of tag end slashes

src/Parser.spec.ts, src/Parser.ts, src/Tokenizer.ts, src/__snapshots__/Tokenizer.spec.ts.snap
Refactors tokenizer callbacks to pass indices instead of strings. This allows us to avoid most string concatenations, which will speed things up in production.
This should also help with memory bloat: V8 [doesn't garbage collect](https://bugs.chromium.org/p/v8/issues/detail?id=2869) strings with slices still being referenced.
Note: AndreasMadsen/htmlparser-benchmark only parses whole documents. As a consequence, there is no speedup with this change.
=> refactor: Don't concatenate strings

package-lock.json, package.json, src/Parser.ts, src/Tokenizer.ts
The decode tree has a slightly different structure, so some adjustments had to be made.
=> Bump entities to 4.1.0

src/Parser.ts, src/Tokenizer.ts
This allows us to avoid the workaround for surrogates. We now simply decode code points in the parser.
=> refactor: Call `replaceCodePoint` in tokenizer

README.md
I think this is important to steer people to htmlparser2 or parse5 based on this key difference, especially since this difference is fundamental and permanent.  It's important to do this up front to save people the time and effort of finding out the hard way.
Fixes #1075
Happy to reword or make any other changes you want, or drop this and leave it all to you :)
=> docs(readme): Add message in README steering people to parse5 if they need HTML5 compliance

.github/workflows/nodejs-test.yml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
=> GitHub Workflows security hardening

README.md
The shields.io badge is broken.
=> docs(readme): Use GitHub Actions CI badge

src/Tokenizer.spec.ts, src/Tokenizer.ts, src/__snapshots__/Tokenizer.spec.ts.snap
Prevents leaking baseState and breaking the Tokenizer if followed by an entity - #1426
=> Reset baseState after closing tag name

package-lock.json, package.json, src/Parser.ts, src/Tokenizer.spec.ts, src/Tokenizer.ts, src/__snapshots__/Tokenizer.spec.ts.snap
`entities` now features an `EntityDecoder` class that closely follows the HTML spec. We can use it here to improve entity parsing performance and accuracy.
The biggest change here is that `htmlparser2` now correctly handles named entities in attributes. `foo=bar&amp=baz` in an attribute will now be left as it is, following the expected behavior from the HTML spec.
=> refactor(tokenizer): Use `EntityDecoder`

src/__snapshots__/index.spec.ts.snap, src/index.spec.ts, src/index.ts
And deprecate `createDomStream`
=> feat(index): Add `createDocumentStream`

src/Parser.ts
There is now an internal `htmlMode` property that caches the use of `!this.options.xmlMode` all across the file. Also `foreignContext` is now reset, and will always contain an element.
=> refactor(parser): Inverse stacks, simplify

src/index.ts
`QuoteType` is need to properly use `onattribend` callback
=> Add export for `QuoteType` in index.ts

src/Tokenizer.spec.ts, src/Tokenizer.ts, src/__snapshots__/Tokenizer.spec.ts.snap, src/__snapshots__/WritableStream.spec.ts.snap, src/__tests__/__snapshots__/events.ts.snap
Fixes https://github.com/fb55/htmlparser2/issues/1538
1. For `NoValue` attributes `endIndex` is set to attribute name's end index
2. For attributes with quotes `endIndex` moved one character forward to match actual attribute end
Output of the script from the ticket:
```
<a aaaaa   >
^
Attribute endIndex: 8
<a aaaaa >
^
Attribute endIndex: 8
<a a=aaa >
^
Attribute endIndex: 8
<a a="a" >
^
Attribute endIndex: 8
```
The fix makes `endIndex` consistent, however I'm a little bit worried that change for quoted attributes may be breaking for someone.
=> Fix Tokenizer onattribend's `endIndex`

src/Tokenizer.spec.ts, src/Tokenizer.ts, src/__snapshots__/Tokenizer.spec.ts.snap
Fixes https://github.com/fb55/htmlparser2/issues/1718
=> fix(tokenizer): treat textarea as special tag

.eslintrc.json, src/Parser.ts, src/WritableStream.ts, src/index.ts
exports the `Handler` interface so consumers who implement typesafe Handlers don't need to do something along the lines of this:
```ts
import type { Parser } from 'htmlparser2';
type Handler = NonNullable<ConstructorParameters<typeof Parser>[0]>;
```
=> feat(Parser): exports Handler interface from Parser
